[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
optimizer = true
via-ir = true
optimizer_runs = 100
solc = "0.8.26"
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mantal_sepolia = "${MANTLE_SEPOLIA_RPC}"