on: [pull_request]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install solc
        run: npm install -g solc@0.8.17

      - name: Install solc
        run: npm install -g solc@0.8.29

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.3.1
        
      - name: Run tests
        run: forge test -vvvv
